FROM jboss/wildfly:10.1.0.Final
MAINTAINER Martín Schonaker <mschonaker@gmail.com>
ADD source/target/ROOT.war /opt/jboss/wildfly/standalone/deployments/
ADD application.properties /opt/jboss/wildfly/standalone/configuration/
